import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Sidebar() {
  return (
    <aside className="fixed left-0 top-0 h-full w-56 bg-[#181818] border-r border-[#00ffe7] z-50 flex flex-col gap-2 p-6 shadow-2xl">
      <span className="text-2xl font-bold text-[#00ffe7] mb-6">Menu</span>
      <Link href="/" className="py-2 px-4 rounded text-lg text-white hover:bg-[#00ffe7] hover:text-[#181818] transition-colors duration-300">Home</Link>
      <Link href="/legeztify" className="py-2 px-4 rounded text-lg text-white hover:bg-[#00ffe7] hover:text-[#181818] transition-colors duration-300">Legeztify</Link>
      <Link href="/legezterest" className="py-2 px-4 rounded text-lg text-white hover:bg-[#00ffe7] hover:text-[#181818] transition-colors duration-300">Legezterest</Link>
      <Link href="/legezttube" className="py-2 px-4 rounded text-lg text-white hover:bg-[#00ffe7] hover:text-[#181818] transition-colors duration-300">LegeztTube</Link>
      <Link href="/legezt-pdf-ai" className="py-2 px-4 rounded text-lg text-white hover:bg-[#00ffe7] hover:text-[#181818] transition-colors duration-300">Legezt PDF AI</Link>
      <Link href="/legezt-ai" className="py-2 px-4 rounded text-lg text-white hover:bg-[#00ffe7] hover:text-[#181818] transition-colors duration-300">Legezt AI</Link>
    </aside>
  );
}

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#111]`}
      >
        <Sidebar />
        <main className="ml-56 min-h-screen">{children}</main>
      </body>
    </html>
  );
}
